import math

"""game settings"""
RES = WIDTH, HEIGHT = 1600, 900
FPS = 60

PLAYER_POSITION = 1.5, 5
PLAYER_ANGLE = 0
PLAYER_SPEED = 0.004
PLAYER_ROTATION = 0.002

FOV = math.pi / 2
RAYSNUM = WIDTH // 2
RAYS_ANGLE = FOV / RAYSNUM
DISTANCE = 20
HALF_RAYSNUM = RAYSNUM // 2
 
